//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlutterWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ftblbarchartdata
    {
        public int ID { get; set; }
        public string year { get; set; }
        public Nullable<int> sales { get; set; }
    }
}
